### ISSUE TITLE
Fix Link in GitHub Repository Description

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/source_span#1]
The link in the description of this repo is incorrect. It currently points to https://pub.dartlang.org/packages/string_scanner

This should be https://pub.dartlang.org/packages/source_span

**Comment by kaendfinger** [comment]
cc @sigmundch @nex3

**Comment by sigmundch** [comment]
Thanks for pointing it out @kaendfinger!

@sethladd, @dgrove, @kevmoo - we don't have admin rights on this repo, can one of you update the description in the settings to update the URL?

**Comment by sethladd** [comment]
Sure thing. I'll also set up an admin group.

On Friday, March 27, 2015, sigmundch <notifications@github.com> wrote:

> Thanks for pointing it out @kaendfinger <https://github.com/kaendfinger>!
>
> @sethladd <https://github.com/sethladd>, @dgrove
> <https://github.com/dgrove>, @kevmoo <https://github.com/kevmoo> - we
> don't have admin rights on this repo, can one of you update the description
> in the settings to update the URL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/source_span/issues/1#issuecomment-87033611>.
>


-- 
Sent from my Motorola Startac

**Comment by kevmoo** [comment]
Fixed! Thanks for the pointer, @kaendfinger

**Comment by kaendfinger** [comment]
Sure
