### ISSUE TITLE
Any solution for disjoint spans?

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/source_span#17]
I use this package a lot via the `SpanScanner` in `package:string_scanner`. However, one difficulty I frequently run into when writing parsers is disjoint span errors when I call `union()`.

This happens when parsing languages that ignore whitespace. For example, I just completed a GraphQL parser, but oftentimes the VM will crash on a disjoint span error before being able to explain the cause of actual syntax errors within GraphQL sources.

Is there any sort of common practice to avoid this?

I know this isn't an issue, per se, but I couldn't think of where else to ask this. Thanks in advance!!!

**Comment by nex3** [comment]
If you're working with `FileSpan`s (which [`SpanScanner`](https://www.dartdocs.org/documentation/string_scanner/1.0.2/string_scanner/SpanScanner-class.html) produces), you can use [the `expand()`  method](https://www.dartdocs.org/documentation/source_span/1.4.0/source_span/FileSpan/expand.html) instead, which creates a span that covers space between two spans as well as the spans themselves.

**Comment by thosakwe** [comment]
Thanks! Didn't know that.
