### ISSUE TITLE
Add Travis CI and Code Coverage

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/source_span#2]
cc @kevmoo

**Comment by nex3** [comment]
This is currently being adequately tested by the package bots. Unless the plan is to move all packages over to Travis, I'd like to keep it consistent with everything else.

**Comment by kaendfinger** [comment]
@nex3 It was my understanding that everything is moving to Travis, I'm not entirely sure though.

**Comment by nex3** [comment]
@ricowind @sigmundch Is that accurate?

**Comment by sigmundch** [comment]
My understanding is that until we get the full matrix of browser coverage in some other way, we were still planning to continue to run tests in the package bots. The other value in using the package bots is that we get clear indications when something fails before we publish an SDK (the package bots trigger every time we modify trunk).

That being said, if there are packages for which there is little value added by having them in the package bots, I wouldn't be opposed to having those tested elsewhere. This is something we have not talked about, though, so I'd first confirm with @ricowind and @kevmoo about it.

Having both Travis + package bots might be overkill, but I'm not opposed to it if it makes it easier to iterate. I think that's a choice each individual package can make if they find it useful. The value added I see is that you can get test results on pull requests.

**Comment by nex3** [comment]
In that case, I think I'd like to keep this on the package bots for the time being. Most of the major patches are done via Rietveld anyway, so I don't think the Travis integration buys us very much, and re-running tests when the SDK updates is very nice.

**Comment by kevmoo** [comment]
One nice thing about travis + coveralls: test coverage

We also get much faster turn-around on builds and automatic sanity checks for pull requests.

We also get coverage for the stable release of Dart – not just bleeding edge.

**Comment by nex3** [comment]
Code coverage is really valuable for large, complex projects, but for a package as simple as this with very few layers between the public API and the implementation, it doesn't provide a lot of benefit on top of manually checking to be sure the API is fully exercised.
